// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_HotelABC.Context;

namespace Proyecto_HotelABC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230725045525_example")]
    partial class example
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto_HotelABC.Entities.Booking", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmountPerson")
                        .HasColumnType("int");

                    b.Property<int?>("CountId")
                        .HasColumnType("int");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("Suite")
                        .HasColumnType("int");

                    b.Property<int?>("SuiteId")
                        .HasColumnType("int");

                    b.Property<int?>("SuiteNamePkName")
                        .HasColumnType("int");

                    b.HasKey("IdReservation");

                    b.HasIndex("CountId");

                    b.HasIndex("SuiteNamePkName");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Proyecto_HotelABC.Entities.Count", b =>
                {
                    b.Property<int>("PkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRole")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkCount");

                    b.HasIndex("FkRole");

                    b.ToTable("Counts");
                });

            modelBuilder.Entity("Proyecto_HotelABC.Entities.Role", b =>
                {
                    b.Property<int>("PkRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Proyecto_HotelABC.Entities.SuiteNames", b =>
                {
                    b.Property<int>("PkName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkName");

                    b.ToTable("SuiteNames");
                });

            modelBuilder.Entity("Proyecto_HotelABC.Entities.Booking", b =>
                {
                    b.HasOne("Proyecto_HotelABC.Entities.Count", "User")
                        .WithMany()
                        .HasForeignKey("CountId");

                    b.HasOne("Proyecto_HotelABC.Entities.SuiteNames", "SuiteName")
                        .WithMany()
                        .HasForeignKey("SuiteNamePkName");

                    b.Navigation("SuiteName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proyecto_HotelABC.Entities.Count", b =>
                {
                    b.HasOne("Proyecto_HotelABC.Entities.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
